# Generated by Django 3.2.13 on 2022-04-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Hotels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HotelName', models.CharField(max_length=50)),
                ('HotelAddress', models.TextField()),
                ('HotelImages', models.ImageField(upload_to='images/')),
                ('Price', models.IntegerField()),
                ('Hotelcategory', models.ManyToManyField(to='home.Category')),
            ],
        ),
    ]
